name: Web App Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.9.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g ionic
        npm install --legacy-peer-deps
        ionic build
 
